# Generated by Django 3.1.7 on 2021-03-16 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='ItemBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='ItemStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(max_length=400)),
                ('price', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('size_height', models.IntegerField()),
                ('size_width', models.IntegerField()),
                ('size_depth', models.IntegerField()),
                ('day_to_ship', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('sold', models.IntegerField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.itembrand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.itemcategory')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.country')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.itemstatus')),
            ],
        ),
    ]
